# Generated by Django 4.2.4 on 2023-08-03 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_blogpost'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogPost',
            new_name='Blog',
        ),
    ]
