# Generated by Django 4.2.4 on 2023-08-04 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_blog_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='опубликовано'),
        ),
    ]
