# Generated by Django 4.2.4 on 2023-08-04 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_blog_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='опубликовано'),
        ),
    ]
