# Generated by Django 4.2.4 on 2023-08-18 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_version'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
